"""Regenerate test-scenarios-data.js — the per-flow scenario registry used by
test-scenarios.js. Run from the repo root:  python scripts/build-test-scenarios.py"""
import glob, json, io, os

SKIP = {"index.html", "404.html", "Component Library 2.html", "component-library.html",
        "studio.html", "homepage.html", "ai-preview.html", "Airtime Inspiration.html",
        "Saving Home Inspiration.html", "Terms & Conditions Inspiration.html"}

FLOWS = [
    ("Airtime Top-up",        ["Airtime"]),
    ("Data Package",          ["Package"]),
    # DSTV is its own multi-screen sub-flow (card, entry, package, add-ons,
    # custom amount); listed before the generic Bill Payment bucket so its five
    # screens don't spill into every other biller's scenario popup.
    ("DSTV",                  ["Bill Payment_DSTV"]),
    ("Bill Payment",          ["Bill Payment", "Pay Bill", "Pay Utility"]),
    ("Merchant Payment",      ["Merchant Payment", "Pay Merchant", "Scan QR", "My QR Code"]),
    ("Send Money & Transfer", ["Send Money", "Transfer", "Transaction Confirmation"]),
    ("Cash In",               ["Cash In", "M-PESA Customer"]),
    ("Withdraw Cash",         ["Withdraw Cash", "Agency Banking Cashout"]),
    ("Saving & Credit",       ["Credit & Saving", "Overdraft"]),
    ("Login & PIN",           ["Login", "PIN-", "Create PIN", "Re-enter PIN", "Forgot-PIN",
                               "OTP Verification", "FingerPrint", "Finger Print"]),
    ("Sign Up & Onboarding",  ["Signup", "SignUp", "Fayda", "Confirm Profile", "App Walkthrough",
                               "first-visit"]),
    ("Account & Statements",  ["Account", "Manage Statement", "Statement PDF", "Transaction History",
                               "Transaction Statment", "Verify Receipt", "Tariffs"]),
    ("Home & Services",       ["Lehulum Home", "More Services", "All Services", "Buy Ticket",
                               "Announcement", "Notification Center", "Update Notice",
                               "Update Request", "Toast Message", "Feedback Tool", "Date Picker",
                               "Favourites", "Favorite"]),
]

ERROR_WORDS = ["Failed", "Insufficient", "Limit Exceeded", "Timeout", "Invalid", "Unavailable",
               "Expired", "Denied", "Locked", "Frozen", "Dormant", "Suspended", "Capped", "Empty",
               "Partial", "No Agents", "Already Used", "Wrong", "Incorrect", "New Account"]


def flow_of(f):
    name = f[:-5].lower()
    for flow, keys in FLOWS:
        if any(k.lower() in name for k in keys):
            return flow
    return None


def label_of(f, cross_flow=False):
    n = f[:-5]
    if cross_flow:
        return n.replace("_", " \u00b7 ")
    for sep in ("_", " - "):
        if sep in n:
            n = n.split(sep, 1)[1]
    return n.strip()


def is_error(f):
    n = f[:-5].lower()
    return any(w.lower() in n for w in ERROR_WORDS)


def main():
    files = [f for f in sorted(glob.glob("*.html")) if f not in SKIP]
    flows, pages = {}, {}

    for f in files:
        fl = flow_of(f)
        if not fl:
            continue
        pages[f] = fl
        entry = flows.setdefault(fl, {"steps": [], "errors": []})
        entry["errors" if is_error(f) else "steps"].append([f, label_of(f)])

    # Overdraft screens live inside other flows but are the substance of Saving & Credit
    od = [[f, label_of(f, cross_flow=True)] for f in files if "overdraft" in f.lower()]
    if od:
        flows.setdefault("Saving & Credit", {"steps": [], "errors": []})["steps"] = od

    data = {"flows": flows, "pages": pages}
    with io.open("test-scenarios-data.js", "w", encoding="utf-8") as out:
        out.write("/* Generated by scripts/build-test-scenarios.py — do not edit by hand. */\n")
        out.write("window.TEST_SCENARIOS_DATA = ")
        out.write(json.dumps(data, ensure_ascii=False, indent=1))
        out.write(";\n")

    missing = {t for e in flows.values() for g in e.values() for t, _ in g if not os.path.exists(t)}
    print("flows: %d | screens: %d | missing targets: %s"
          % (len(flows), len(pages), sorted(missing) or "none"))


if __name__ == "__main__":
    main()
